/**
 * 
 */
package game;

/**
 * @author Ben
 *
 */
public class WinnerScreen extends javax.swing.JFrame {

  /**
   * Creates new form WinnerScreen
   */
  public WinnerScreen() {
      initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
  private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
      jLabel1.setText("Player 1 Wins!");

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel2.setText("Player 1 Wins: 8");

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
      jLabel3.setText("Player 2 Wins: 4");

      jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jButton1.setText("Play Again");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
              jButton1ActionPerformed(evt);
          }
      });

      jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jButton2.setText("Quit");
      jButton2.setMaximumSize(new java.awt.Dimension(95, 25));
      jButton2.setMinimumSize(new java.awt.Dimension(95, 25));
      jButton2.setPreferredSize(new java.awt.Dimension(95, 25));
      jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
              .addGap(95, 95, 95)
              .addComponent(jButton1)
              .addGap(18, 18, 18)
              .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
              .addContainerGap(125, Short.MAX_VALUE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel1)
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGap(125, 125, 125))
      );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
              .addGap(20, 20, 20)
              .addComponent(jLabel1)
              .addGap(18, 18, 18)
              .addComponent(jLabel2)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(jLabel3)
              .addGap(35, 35, 35)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addContainerGap(32, Short.MAX_VALUE))
      );

      pack();
  }// </editor-fold>                        

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      // TODO add your handling code here:
  }   
  
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    System.exit(0);
} 

/*  public static void main(String args[])
  {
  		WinnerScreen ws = new WinnerScreen();
  		ws.setVisible(true);
  }
*/
  // Variables declaration - do not modify                     
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration                   
}
